apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-zzkkvbua
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/quay_xjiang/go-zzkkvbua:e6bfe19e0bd8cba2c4fc28eb5bdaa1ddc44f5030@sha256:88055f99de31e00034b228dc9dd63ce508f93387447228b6ef7dbae27faa1391
          name: container-image
